"""交易

Revision ID: 4275bdbbe821
Revises: 26d9285f79f0
Create Date: 2025-11-13 19:51:55.155915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4275bdbbe821'
down_revision = '26d9285f79f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancel_time')

    # ### end Alembic commands ###
