"""实现买卖家对话

Revision ID: 580d884c22a8
Revises: 4275bdbbe821
Create Date: 2025-11-27 10:22:58.540994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '580d884c22a8'
down_revision = '4275bdbbe821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('buyer_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seller_read', sa.Boolean(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('cancel_reason',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('cancel_reason',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_bin'),
               existing_nullable=True)

    with op.batch_alter_table('contact_request', schema=None) as batch_op:
        batch_op.drop_column('seller_read')
        batch_op.drop_column('buyer_read')
        batch_op.drop_column('reply')

    # ### end Alembic commands ###
